# Generated by Django 5.0.6 on 2024-09-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player2',
            name='user',
        ),
        migrations.AddField(
            model_name='player2',
            name='username',
            field=models.CharField(default='anonyme-player2', max_length=150, unique=True),
        ),
    ]
