# Generated by Django 5.0.6 on 2024-12-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_remove_player2_user_player2_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingqueue2',
            name='player',
        ),
        migrations.DeleteModel(
            name='GameRoom2',
        ),
        migrations.DeleteModel(
            name='MatchmakingQueue2',
        ),
        migrations.DeleteModel(
            name='Player2',
        ),
    ]
