# Generated by Django 5.0.6 on 2024-12-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingqueue1',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='player1',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameRoom1',
        ),
        migrations.DeleteModel(
            name='MatchmakingQueue1',
        ),
        migrations.DeleteModel(
            name='Player1',
        ),
    ]
