# Generated by Django 5.0.6 on 2024-12-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingqueue',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameRoom',
        ),
        migrations.DeleteModel(
            name='MatchmakingQueue',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
