# Generated by Django 5.0.6 on 2024-12-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remoteTournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingqueue3',
            name='player',
        ),
        migrations.RemoveField(
            model_name='remotematch',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='remotematch',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='remotematch',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='remotematch',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='remoteparticipant',
            name='player',
        ),
        migrations.RemoveField(
            model_name='remoteparticipant',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='remoteplayer',
            name='current_tournament',
        ),
        migrations.RemoveField(
            model_name='remotetournament',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='remoteround',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='GameRoom3',
        ),
        migrations.DeleteModel(
            name='MatchmakingQueue3',
        ),
        migrations.DeleteModel(
            name='RemoteMatch',
        ),
        migrations.DeleteModel(
            name='RemoteParticipant',
        ),
        migrations.DeleteModel(
            name='RemotePlayer',
        ),
        migrations.DeleteModel(
            name='RemoteRound',
        ),
        migrations.DeleteModel(
            name='RemoteTournament',
        ),
    ]
